apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: us-east-2
  version: '1.25'
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t2.small
  volumeSize: 20
