apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata:
      labels:
        app: marketplace
    spec:
      containers:
      - name: marketplace
        image: mikronman/my-docker-app:latest
        ports:
        - containerPort: 8081
